services:
  postgres:
    image: postgres:17-alpine
    container_name: chatapp_db
    environment:
      POSTGRES_DB: realtime_chat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5436:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: