spring:
  application:
    name: realtime-chat
  thymeleaf:
    cache: false
  messages:
    basename: i18n/messages
    fallback-to-system-locale: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:replace-with-google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:replace-with-google-client-secret}
            scope:
              - openid
              - profile
              - email

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5436/realtime_chat}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
  
server:
  port: 8080
